topics_to_record : ['/tf',
                     '/atlas/joint_states',
                     '/atlas/joint_states_throttled',
                     '/atlas/sensed_joint_states',
                     '/atlas/atlas_state',
                     '/atlas/atlas_state_throttled',
                     '/atlas/atlas_sim_interface_state_throttled',
                     '/atlas/atlas_command_throttled',
                     '/atlas/atlas_sim_interface_command',
                     '/atlas/atlas_sim_interface_command_throttled',
                     '/bdi_manipulate_pelvis_pose_rpy_throttled',
                     '/flor/controller/stability',
                     '/flor/state/pelvis_pose_world',
                     '/flor/controller/atlas_pose_throttled',
                     '/flor/controller/atlas_pose',
                     '/flor/pelvis_controller/current_states',
                     '/flor/pelvis_controller/joint_states',
                     '/flor/pelvis_controller/pelvis_states',
                     '/flor/pelvis_controller/trajectory',
                     '/multisense_sl/laser/scan']

