topics_to_record : ['/flor/controller/atlas_state',
                    '/flor/controller/joint_command',
                    '/trajectory_controllers/right_arm_traj_controller/follow_joint_trajectory/feedback',
                    '/trajectory_controllers/right_arm_traj_controller/follow_joint_trajectory/goal',
                    '/trajectory_controllers/left_arm_traj_controller/follow_joint_trajectory/feedback',
                    '/trajectory_controllers/left_arm_traj_controller/follow_joint_trajectory/goal',
                    '/tf',
                    '/atlas/joint_states_throttled',
                    '/atlas/sensed_joint_states',
                    '/atlas/atlas_state_throttled',
                    '/atlas/atlas_sim_interface_state_throttled',
                    '/atlas/atlas_command_throttled',
                    '/atlas/atlas_sim_interface_command_throttled',
                    '/bdi_manipulate_pelvis_pose_rpy_throttled',
                    '/flor/controller/stability',
                    '/flor/state/pelvis_pose_world',
                    '/flor/controller/atlas_pose_throttled',
                    '/flor/pelvis_controller/current_states',
                    '/flor/pelvis_controller/joint_states',
                    '/flor/pelvis_controller/pelvis_states',
                    '/flor/pelvis_controller/trajectory']

