topics_to_record : ['/flor/controller/atlas_state',
                    '/flor/controller/joint_command',
                    '/flor/controller/joint_control',
                    '/flor/controller/actuator_state',
                    '/flor/controller/raw_actuator',
                    '/flor/controller/interface_statistics',
                    '/flor/controller/controller_statistics',
                    '/flor/controller/mode',
                    '/flor/controller/raw_state',
                    '/flor/controller/robot_status',
                    '/flor/controller/wrist_strain',
                    '/trajectory_controllers/right_arm_traj_controller/follow_joint_trajectory/status',
                    '/trajectory_controllers/right_arm_traj_controller/follow_joint_trajectory/feedback',
                    '/trajectory_controllers/right_arm_traj_controller/follow_joint_trajectory/result',
                    '/trajectory_controllers/right_arm_traj_controller/follow_joint_trajectory/goal',
                    '/trajectory_controllers/left_arm_traj_controller/follow_joint_trajectory/status',
                    '/trajectory_controllers/left_arm_traj_controller/follow_joint_trajectory/feedback',
                    '/trajectory_controllers/left_arm_traj_controller/follow_joint_trajectory/result',
                    '/trajectory_controllers/left_arm_traj_controller/follow_joint_trajectory/goal',
                    '/trajectory_controllers/right_arm_traj_impedance_controller/follow_joint_trajectory/status',
                    '/trajectory_controllers/right_arm_traj_impedance_controller/follow_joint_trajectory/feedback',
                    '/trajectory_controllers/right_arm_traj_impedance_controller/follow_joint_trajectory/result',
                    '/trajectory_controllers/right_arm_traj_impedance_controller/follow_joint_trajectory/goal',
                    '/trajectory_controllers/left_arm_traj_impedance_controller/follow_joint_trajectory/status',
                    '/trajectory_controllers/left_arm_traj_impedance_controller/follow_joint_trajectory/feedback',
                    '/trajectory_controllers/left_arm_traj_impedance_controller/follow_joint_trajectory/result',
                    '/trajectory_controllers/left_arm_traj_impedance_controller/follow_joint_trajectory/goal',
                    '/robot_controllers/right_arm_joint_impedance_controller/dyn_rec/right_arm/parameter_updates',
                    '/robot_controllers/left_arm_joint_impedance_controller/dyn_rec/left_arm/parameter_updates',
                    '/robot_controllers/left_arm_joint_impedance_controller/tau_obs',
                    '/robot_controllers/right_arm_joint_impedance_controller/tau_obs']
