# Competition configuration options
options:
  insert_models_over_bins: true
  belt_population_cycles: 3


orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    destinations: [agv1]
    products:
      part_0:
        type: gasket_part
        pose:
          xyz: [0.1, -0.1, 0]
          rpy: [0, 0, 'pi/4']
      part_1:
        type: gear_part
        pose:
          xyz: [-0.1, 0, 0]
          rpy: [0, 0, 0]

  order_1:
    announcement_condition: time
    announcement_condition_value: 60.0
    shipment_count: 1
    destinations: [agv2]
    products:
      part_0:
        type: gasket_part
        pose:
          xyz: [0.1, -0.1, 0]
          rpy: [0, 0, 'pi/4']
      part_1:
        type: piston_rod_part
        pose:
          xyz: [-0.1, 0, 0]
          rpy: [0, 0, 'pi/4']

models_over_bins:

  bin3:
    models:
      piston_rod_part:
        xyz_start: [0.15, 0.1, 0.0]
        xyz_end: [0.5, 0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3
  bin4:
    models:
      gear_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 4
  bin5:
    models:
      gasket_part:
        xyz_start: [0.1, 0.15, 0.0]
        xyz_end: [0.4, 0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 3


belt_models:
  piston_rod_part:
    2.0:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 'pi/4']
  gasket_part:
    4.0:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 'pi/4']
  gear_part:
    6.0:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 0]


time_limit: -1
