sensors:
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, -0.38, 0.91]
      rpy: [0, 0, 'pi']
  proximity_sensor_1:
    type: proximity_sensor
    pose:
      xyz: [0.95, 2.6, 0.92]
      rpy: [0, 0, 0]
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [-0.3, -1.91, 1.6]
      rpy: [0, pi/2, 0]
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [-0.3, -1.15, 1.6]
      rpy: [0, pi/2, 0]
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [-0.3, -0.383, 1.6]
      rpy: [0, pi/2, 0]
  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [-0.3, 0.383, 1.6]
      rpy: [0, pi/2, 0]
  logical_camera_5:
    type: logical_camera
    pose:
      xyz: [-0.3, 1.15, 1.6]
      rpy: [0, pi/2, 0]
  logical_camera_6:
    type: logical_camera
    pose:
      xyz: [-0.3, 1.91, 1.6]
      rpy: [0, pi/2, 0]
  logical_camera_7:
    type: logical_camera
    pose:
      xyz: [1.3, -0.38, 1.6]
      rpy: [0, pi/2, 0]
  laser_profiler_1:
    type: laser_profiler
    pose:
      xyz: [1.21, 4, 1.6]
      rpy: ['-pi', 'pi/2', 'pi/2']
